version: '3'
services:
    app:
        build:
            context: docker
            dockerfile: php
        environment:
            - SLACK_WEBHOOK_URL
            - CURRENCY
            - TIMESTAMPS
            - INLINE
            - LOCALE
            - PRICE_CHANGE_DIFF
        volumes:
            - .:/code
