#!/usr/bin/env bash

declare -a required_variables=("SLACK_WEBHOOK_URL")

for i in "${required_variables[@]}"
do
   if [ -z "${!i}" ]; then
       echo "$i environment variable is not set"
       exit 1
   fi
done

if [ ! -d vendor ]; then
    ./docker/composer install
fi

if [ -z $CURRENCY ]; then
    export CURRENCY=USD
fi

if [ -z $LOCALE ]; then
    export LOCALE=en_US
fi

if [ -z $PRICE_CHANGE_DIFF ]; then
    export PRICE_CHANGE_DIFF=true
fi

docker-compose run app php /code/slackcoin.php
